Added function for save restart of apache2

diff --git a/source/etc/kirbyfunctions b/source/etc/kirbyfunctions
--- a/source/etc/kirbyfunctions
+++ b/source/etc/kirbyfunctions
@@ -342,3 +342,27 @@ function save_ln { # $1=sourcefile $2=targetfile or targetdir
   fi
   debMsg "Leaving function $FUNCNAME"
 }
+
+## Try apache2 configtest and restart if ok
+function restart_apache2 {
+  debMsg "Entering function $FUNCNAME"
+  echo -n "Testing apache2 configuration (with 'sudo apache2ctl configtest') ..."
+  CONFIGTEST=$(sudo apache2ctl configtest 2>&1 > /dev/null)
+  ERR=$?
+  if [ "$ERR" != "0" ];then
+    echo -e "${txtred}failed.${txtrst}\n"
+    errMsg $CONFIGTEST
+  else
+    echo -e "${txtgreen}successful.${txtrst}"
+    echo -n "Restarting apache2 (with 'sudo apache2ctl graceful') ..."
+    GRACEFUL=$(sudo apache2ctl graceful 2>&1 > /dev/null)
+    ERR=$?
+    if [ "$ERR" != "0" ];then
+      echo -e "${txtred}failed.${txtrst}\n"
+      errMsg $GRACEFUL
+    else
+      echo -e "${txtgreen}successful.${txtrst}"
+    fi
+  fi
+  debMsg "Leaving function $FUNCNAME"
+}
